update 4.2.5.2
whatwg-cn/html pull request #24
Opened 2021-05-16 09:43 UTC by redhat123456

请指教✨✨

2021-06-15 11:39 UTC, harttle requested changes
抱歉这么久才看。除了评论的之外，还有 bin 下的文件权限变更不应该提交上来。同样可以 git checkout 出原版，或者重新 commit 前不要 add 这些不是故意提交的文件。

2021-06-15 11:39 UTC, harttle commented on src/the-elements-of-html/embedded-content/images/requirements-for-providing-text-to-act-as-an-alternative-for-images/an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images.zh.html
> -  <h6 id="an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images">给特定的、已知一定可以查看图片的人的 e-mail 或私人文档中的图片</h6>
这个文件不应该删除，编译崩是因为找不到这个文件了。可以

```bash
git checkout origin/master src/the-elements-of-html/embedded-content/images/requirements-for-providing-text-to-act-as-an-alternative-for-images/an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images.zh.html
git add src/the-elements-of-html/embedded-content/images/requirements-for-providing-text-to-act-as-an-alternative-for-images/an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images.zh.html
```

再提交。

2021-06-15 11:39 UTC, harttle commented on src/the-elements-of-html/embedded-content/images/requirements-for-providing-text-to-act-as-an-alternative-for-images/an-image-in-an-email-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images.en.html
> -  <h6 id="an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images">An image in an email or private document intended for a specific person who
同上，这个文件也不应该被删除。

2021-06-16 09:28 UTC, redhat123456 commented on src/the-elements-of-html/embedded-content/images/requirements-for-providing-text-to-act-as-an-alternative-for-images/an-image-in-an-email-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images.en.html
> -  <h6 id="an-image-in-an-e-mail-or-private-document-intended-for-a-specific-person-who-is-known-to-be-able-to-view-images">An image in an email or private document intended for a specific person who
好的谢谢

2022-05-21 11:01 UTC, harttle commented
Closing since the commit [3f53bbd](https://github.com/whatwg-cn/html/pull/24/commits/3f53bbd88b284d9d11e8f420b3017332e4b1ed44) has already merged.

2022-05-21 11:01 UTC, closed without merging